name: Docker Build

# Controls when the workflow will run
on:
  workflow_dispatch:
  release:
    types: [ created ]


jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/webhook
          flavor: latest=true
          tags: |
            type=semver,pattern={{raw}},value=${{ github.event.release.name }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/webhook:latest,ghcr.io/${{ github.repository_owner }}/webhook:${{ github.event.release.name }}
